name = "parallel_map"
version = "3.0.1"

description = "A simple parallel map library in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "PastMoments", repo = "parallel_map" }

target = "erlang"

internal_modules = [
  "parallel_map/internal",
  "parallel_map/internal/*"
]

[dependencies]
gleam_erlang = ">= 0.33.0 and < 1.0.0"
gleam_yielder = ">= 1.1.0 and < 2.0.0"
gleam_stdlib = ">= 0.50.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
